# Generated by Django 4.0 on 2022-02-05 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200, verbose_name='Вопрос')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
                'db_table': 'polls',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(max_length=200, verbose_name='Опрос')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='choices', to='webapp.poll', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Варианта ответa',
                'verbose_name_plural': 'Варианты ответов',
                'db_table': 'choices',
            },
        ),
    ]
